# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CalebDevelops
email: calebashmoreadams@gmail.com	
description: > # this means to ignore newlines until "baseurl:"
  Caleb Adams is a NASA flight software developer, systems engineer, and hacker. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://calebdevelops.com" # the base hostname & protocol for your site
twitter_username: piepieninja
github_username:  piepieninja

# Build settings
markdown: kramdown
